### ISSUE TITLE
DevEnvironment: Error log

### ISSUE THREAD

**Issue by dominijk** [tomalrussell/colouring-london#302]
From mac install

```
    default: + chown -R vagrant:vagrant /home/vagrant/colouringlondon
    default: + npm install -g npm@next
    default: /usr/local/lib/node/node-v8.11.3/bin/npm -> /usr/local/lib/node/node-v8.11.3/lib/node_modules/npm/bin/npm-cli.js
    default: /usr/local/lib/node/node-v8.11.3/bin/npx -> /usr/local/lib/node/node-v8.11.3/lib/node_modules/npm/bin/npx-cli.js
    default: + npm@6.9.1-next.0
    default: added 312 packages, removed 364 packages and updated 53 packages in 7.59s
    default: + cd /vagrant/app
    default: + npm install
    default: npm
    default:  
    default: ERR!
    default:  
    default: path
    default:  /vagrant/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/package.json.2948920491
    default: npm
    default:  
    default: ERR!
    default:  
    default: code
    default:  ENOENT
    default: npm
    default:  
    default: ERR!
    default:  
    default: errno
    default:  -2
    default: npm
    default:  
    default: ERR!
    default:  
    default: syscall
    default:  open
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  ENOENT: no such file or directory, open '/vagrant/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/package.json.2948920491'
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  This is related to npm not being able to find a file.
    default: npm
    default:  
    default: ERR!
    default:  
    default: enoent
    default:  
    default: npm
    default:  
    default: ERR!
    default:  A complete log of this run can be found in:
    default: npm
    default:  
    default: ERR!
    default:      /root/.npm/_logs/2019-06-20T13_59_38_392Z-debug.log
    default: + tr -d '\r'
    default: + chown vagrant:vagrant /home/vagrant/.bashrc
```
